name: test
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Install Packages
        run: go mod download

      - name: Run
        run: go test -cover ./...
